
export const ROLES = {
  PATIENT: 'PATIENT',
  DOCTOR: 'DOCTOR',
  DELIVERY_PARTNER : 'DELIVERY_PARTNER',
  ORHANISATION:{ 
     EMPLOYEE:{ 
      DIAGNOSTICIAN:'DIAGNOSTICIAN',
      ORGANISATION_RECEIPTIONIST :'ORGANISATION_RECEIPTIONIST',
  },
    ORGANIZATION_ADMIN :'ORGANIZATION_ADMIN'
},
  PHARMACY:'SELLER',
  ADMIN: {
    SUPERADMIN:'SUPERADMIN',
    ADMIN:'ADMIN'
  }
} as const;


export type UserRole = typeof ROLES[keyof typeof ROLES];