import React, { useState } from "react";
import { Link } from "react-router-dom";
import {
  Mail,
  Lock,
  Eye,
  EyeOff,
  AlertCircle,
  KeyRound,
  ShieldCheck,
} from "lucide-react";
import { AuthCard } from "../components/AuthCard";
import { GoogleLogin } from "@react-oauth/google";
import { useAuth } from "../hooks/useAuth";
import { authApi } from "../api/auth.api";
import { ROUTES } from "@/constants/routes.constants";

export function LoginPage() {
  const { login, verifyMfaLogin, mfaPending, isLoading, error, clearError } = useAuth();

  const [emailOrPhone, setEmailOrPhone] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [mfaCode, setMfaCode] = useState("");
  const [validationError, setValidationError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setValidationError(null);
    clearError();

    if (!emailOrPhone.trim()) {
      setValidationError("Please enter your email address.");
      return;
    }

    if (!password) {
      setValidationError("Please enter your password.");
      return;
    }

    try {
      await login({
        email: emailOrPhone.trim(),
        password,
      });
    } catch (err: any) {
      let msg =
        err?.response?.data?.error?.message ||
        err?.response?.data?.message;

      if (!msg) {
        if (err.code === "ECONNABORTED" || err?.message?.includes("timeout")) {
          msg = "The server took too long to respond (timeout). The backend may be waking up from idle on Render. Please wait a moment and try again.";
        } else if (err.message === "Network Error" || err.code === "ERR_NETWORK") {
          msg = "Unable to connect to the backend server. Please check your connection or backend service status.";
        } else {
          msg = err?.message || "Invalid email or password.";
        }
      }
      setValidationError(msg);
    }
  };

  const handleMfaSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setValidationError(null);
    clearError();

    if (!mfaPending?.challengeToken) {
      setValidationError("MFA session expired. Please sign in again.");
      return;
    }

    if (!mfaCode.trim()) {
      setValidationError("Please enter the verification code from your authenticator.");
      return;
    }

    try {
      await verifyMfaLogin({
        challengeToken: mfaPending.challengeToken,
        code: mfaCode.trim(),
      });
    } catch (err: any) {
      const msg =
        err?.response?.data?.error?.message ||
        err?.response?.data?.message ||
        err?.message ||
        "Invalid authenticator code. Please try again.";
      setValidationError(msg);
    }
  };

  const [isGoogleLoading, setIsGoogleLoading] = useState(false);

  const handleGoogleCredential = async (idToken: string) => {
    try {
      setIsGoogleLoading(true);
      clearError();
      setValidationError(null);

      const response = await authApi.googleAuth(idToken);
      if (!response) {
        setValidationError("No response from server. Please try again.");
        return;
      }

      const accessToken = response.accessToken || response.AccessToken;
      const user = response.user;

      if (accessToken) {
        localStorage.setItem("AccessToken", accessToken);
      }

      const { getRoleDashboardPath } = await import("../hooks/useAuth");
      const path = getRoleDashboardPath(user?.userType ?? "PATIENT");
      window.location.href = path;
    } catch (err: any) {
      const serverMsg =
        err?.response?.data?.error?.message ||
        err?.response?.data?.message ||
        err?.message;

      if (err?.response?.status === 409) {
        setValidationError(
          "An account with this Google email already exists. Please sign in with your password instead."
        );
      } else {
        setValidationError(serverMsg ?? "Google sign-in failed. Please try again.");
      }
    } finally {
      setIsGoogleLoading(false);
    }
  };

  return (
    <AuthCard
      title={mfaPending?.required ? "Two-Factor Verification" : "Welcome Back"}
      subtitle={
        mfaPending?.required
          ? "Enter the code generated by your authenticator app"
          : "Sign in to your ArogyaGenie healthcare account"
      }
      badge={mfaPending?.required ? "2FA Security" : "Secure Portal"}
      maxWidth="w-full max-w-[280px] sm:max-w-sm md:max-w-md mx-auto"
      footer={
        <p className="text-center text-[10px] sm:text-xs text-slate-400">
          Don't have an account?{" "}
          <Link
            to={ROUTES.AUTH.REGISTER}
            className="font-semibold text-indigo-400 hover:text-indigo-300 transition-colors"
          >
            Sign up now
          </Link>
        </p>
      }
    >
      <div className="w-full space-y-2 sm:space-y-2.5">
        {/* Error Alert */}
        {/* {(error || validationError) && (
          <div className="p-2.5 rounded-xl bg-red-500/15 border border-red-500/30 flex items-start gap-2 text-red-200 text-xs animate-fadeIn">
            <AlertCircle className="h-4 w-4 shrink-0 mt-0.5 text-red-400" />
            <span className="flex-1 leading-snug">{error || validationError}</span>
          </div>
        )} */}

        {(error || validationError) && (
          <div className="p-1 sm:p-2 rounded-md sm:rounded-xl bg-red-500/10 border border-red-500/20 flex items-start gap-1.5 text-red-300 text-[10px] sm:text-xs animate-fadeIn">
            <AlertCircle className="h-3 w-3 sm:h-3.5 sm:w-3.5 shrink-0 mt-0.5 text-red-400" />
            <span className="flex-1 leading-tight sm:leading-snug break-words">
              {error || validationError}
            </span>
          </div>
        )}

        {mfaPending?.required ? (
          /* MFA Challenge Form */
          <form onSubmit={handleMfaSubmit} className="space-y-2 sm:space-y-2.5 animate-fadeIn">
            <div className="text-center py-1 sm:py-2">
              <div className="h-8 w-8 sm:h-10 sm:w-10 rounded-full bg-indigo-500/15 text-indigo-400 flex items-center justify-center mx-auto border border-indigo-500/30 mb-1.5">
                <ShieldCheck className="h-4 w-4 sm:h-5 sm:w-5" />
              </div>
              <p className="text-[10px] sm:text-xs text-slate-300 leading-relaxed">
                Your account is protected with Multi-Factor Authentication. Please enter your 6-digit verification code.
              </p>
            </div>

            <div className="space-y-0.5">
              <label className="text-[9px] sm:text-xs font-medium text-slate-300 block">
                6-Digit Authenticator Code
              </label>
              <div className="relative w-full">
                <KeyRound className="absolute left-2.5 sm:left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-400" />
                <input
                  type="text"
                  autoFocus
                  maxLength={8}
                  value={mfaCode}
                  onChange={(e) => setMfaCode(e.target.value)}
                  placeholder="123456"
                  className="w-full pl-8 sm:pl-9 pr-3 py-1 sm:py-2 rounded-md sm:rounded-xl border border-white/10 bg-slate-900/40 text-white placeholder-slate-500 text-[11px] sm:text-sm tracking-widest font-mono text-center focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-all box-border"
                />
              </div>
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="w-full flex items-center justify-center py-1.5 sm:py-2.5 px-3 sm:px-4 rounded-md sm:rounded-xl font-semibold text-xs sm:text-sm text-white shadow-md shadow-indigo-600/30 bg-linear-to-r from-indigo-600 to-indigo-500 hover:from-indigo-500 hover:to-indigo-400 active:scale-[0.99] transition-all duration-150 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed mt-1 text-center"
            >
              {isLoading ? (
                <span className="inline-flex items-center gap-1.5">
                  <span className="h-2.5 w-2.5 sm:h-3.5 sm:w-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin shrink-0" />
                  <span>Verifying Code...</span>
                </span>
              ) : (
                <span className="inline-flex items-center gap-1.5">
                  <ShieldCheck className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
                  <span>Verify & Complete Sign In</span>
                </span>
              )}
            </button>
          </form>
        ) : (
          /* Regular Login Form */
          <>
            <form onSubmit={handleSubmit} className="space-y-1.5 sm:space-y-2.5">
              {/* Email Input */}
              <div className="space-y-0.5">
                <label className="text-[9px] sm:text-xs font-medium text-slate-300 block">
                  Email Address
                </label>
                <div className="relative w-full">
                  <Mail className="absolute left-2 sm:left-3 top-1/2 -translate-y-1/2 h-3 w-3 sm:h-3.5 sm:w-3.5 text-slate-400" />
                  <input
                    type="email"
                    required
                    value={emailOrPhone}
                    onChange={(e) => setEmailOrPhone(e.target.value)}
                    placeholder="e.g. user@arogyagenie.com"
                    className="w-full pl-7 sm:pl-9 pr-3 py-1 sm:py-2 rounded-md sm:rounded-xl border border-white/10 bg-slate-900/40 text-white placeholder-slate-500 text-[11px] sm:text-sm focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-all box-border"
                  />
                </div>
              </div>

              {/* Password Input */}
              <div className="space-y-0.5">
                <div className="flex items-center justify-between">
                  <label className="text-[9px] sm:text-xs font-medium text-slate-300">Password</label>
                  <Link
                    to={ROUTES.AUTH.FORGOT_PASSWORD}
                    className="text-[8px] sm:text-[10px] text-indigo-400 hover:text-indigo-300 transition-colors"
                  >
                    Forgot password?
                  </Link>
                </div>
                <div className="relative w-full">
                  <Lock className="absolute left-2 sm:left-3 top-1/2 -translate-y-1/2 h-3 w-3 sm:h-3.5 sm:w-3.5 text-slate-400" />
                  <input
                    type={showPassword ? "text" : "password"}
                    required
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="Enter your password"
                    className="w-full pl-7 sm:pl-9 pr-7 sm:pr-8 py-1 sm:py-2 rounded-md sm:rounded-xl border border-white/10 bg-slate-900/40 text-white placeholder-slate-500 text-[11px] sm:text-sm focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-all box-border"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-1.5 sm:right-2.5 top-1/2 -translate-y-1/2 text-slate-400 hover:text-white transition-colors cursor-pointer"
                    aria-label={showPassword ? "Hide password" : "Show password"}
                  >
                    {showPassword ? <EyeOff className="h-2.5 w-2.5 sm:h-3.5 sm:w-3.5" /> : <Eye className="h-2.5 w-2.5 sm:h-3.5 sm:w-3.5" />}
                  </button>
                </div>
              </div>

              {/* Submit Button */}
              <button
                type="submit"
                disabled={isLoading}
                className="w-full flex items-center justify-center py-1.5 sm:py-2.5 px-3 sm:px-4 rounded-md sm:rounded-xl font-semibold text-xs sm:text-sm text-white shadow-md shadow-indigo-600/30 bg-linear-to-r from-indigo-600 to-indigo-500 hover:from-indigo-500 hover:to-indigo-400 active:scale-[0.99] transition-all duration-150 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed mt-1 text-center"
              >
                {isLoading ? (
                  <span className="inline-flex items-center gap-1.5">
                    <span className="h-2.5 w-2.5 sm:h-3.5 sm:w-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin shrink-0" />
                    <span>Signing in...</span>
                  </span>
                ) : (
                  <span>Sign In</span>
                )}
              </button>
            </form>

            {/* Compact Divider */}
            <div className="flex items-center gap-2 my-1">
              <div className="h-px flex-1 bg-white/10" />
              <span className="text-[9px] uppercase tracking-widest text-slate-500 font-medium">Or</span>
              <div className="h-px flex-1 bg-white/10" />
            </div>

            {/* Google Sign In */}
            {/* <div className="flex justify-center">
              {isGoogleLoading ? (
                <div className="flex items-center gap-2 text-xs text-slate-400 py-1">
                  <span className="h-3.5 w-3.5 border-2 border-slate-400/30 border-t-slate-400 rounded-full animate-spin" />
                  Connecting to Google...
                </div>
              ) : (
                <GoogleLogin
                  onSuccess={(credentialResponse) => {
                    if (credentialResponse.credential) {
                      handleGoogleCredential(credentialResponse.credential);
                    } else {
                      setValidationError("Google sign-in failed: no credential received.");
                    }
                  }}
                  onError={() => {
                    setValidationError("Google sign-in failed. Please try again.");
                  }}
                  theme="filled_black"
                  shape="pill"
                  text="continue_with"
                  size="medium"
                  width="320"
                />
              )}
            </div> */}
          </>
        )}
      </div>
    </AuthCard>
  );
}

export default LoginPage;